site_name: Et cetera Docs

site_url: https://etc.hneu.edu.ua/docs/

nav:
    - 'Нотатки адміністратора':
        - 'Розгортання та забезпечення безпеки': 'index.md'
        - 'Проведення наукових конференцій': 'conference.md'
        - 'Встановлення Kali Linux': 'kaliwindows.md'
        - 'Сканування вразливостей сайту на Wordpress': 'wpscan.md'
        - 'Сканер вразливостей Nessus': 'nessus.md'
        - 'Як встановити Django': 'djangoubuntu.md'
    - 'Про проект': about.md

repo_url: https://github.com/texnotes/sitesdocs/
edit_uri: ""

plugins:
  - search:
      lang:
        - en
        - ru

copyright: Copyright &copy; 2020 <a href="https://www.hneu.edu.ua">ХНЕУ ім. С. Кузнеця</a>, кафедра <a href="http://www.kafcbit.hneu.edu.ua">Кібербезпеки та інформаційних технологій</a>.


